# recreate_db.py

from api.infra.sqlalchemy.config.db import engine, Base, create_db, SessionLocal
from api.infra.sqlalchemy.models import models
from api.infra.sqlalchemy.models.models import Discipline



def recreate_db():
    # Remove todas as tabelas existentes
    print("Dropping all tables...")
    Base.metadata.drop_all(bind=engine)
    
    # Cria as tabelas a partir dos modelos importados
    print("Creating all tables...")
    Base.metadata.create_all(bind=engine)
    print("Banco de dados recriado com sucesso!")

disciplines_data = [
    ("CIC0004", "ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES"),
    ("FGA0163", "INTRODUÇÃO À ENGENHARIA"),
    ("FGA0168", "DESENHO INDUSTRIAL ASSISTIDO POR COMPUTADOR"),
    ("FGA0302", "ENGENHARIA E AMBIENTE"),
    ("MAT0025", "CÁLCULO 1"),
    ("FGA0157", "PROBABILIDADE E ESTATÍSTICA APLICADO A ENGENHARIA"),
    ("IFD0171", "FISICA 1"),
    ("IFD0173", "FISICA 1 EXPERIMENTAL"),
    ("MAT0026", "CÁLCULO 2"),
    ("MAT0031", "INTRODUCAO A ALGEBRA LINEAR"),
    ("FGA0071", "PRÁTICA DE ELETRÔNICA DIGITAL 1"),
    ("FGA0073", "TEORIA DE ELETRÔNICA DIGITAL 1"),
    ("FGA0085", "MATEMÁTICA DISCRETA 1"),
    ("FGA0133", "ENGENHARIA ECONÔMICA"),
    ("FGA0158", "ORIENTAÇÃO A OBJETOS"),
    ("FGA0160", "MÉTODOS NUMÉRICOS PARA ENGENHARIA"),
    ("FGA0164", "HUMANIDADES E CIDADANIA"),
    ("FGA0108", "MATEMÁTICA DISCRETA 2"),
    ("FGA0142", "FUNDAMENTOS DE ARQUITETURA DE COMPUTADORES"),
    ("FGA0146", "ESTRUTURAS DE DADOS 1"),
    ("FGA0303", "PROJETO INTEGRADOR DE ENGENHARIA 1"),
    ("FGA0307", "GESTÃO DA PRODUÇÃO E QUALIDADE"),
    ("FGA0312", "MÉTODOS DE DESENVOLVIMENTO DE SOFTWARE"),
    ("FGA0003", "COMPILADORES 1"),
    ("FGA0030", "ESTRUTURAS DE DADOS 2"),
    ("FGA0137", "SISTEMAS DE BANCO DE DADOS 1"),
    ("FGA0170", "FUNDAMENTOS DE SISTEMAS OPERACIONAIS"),
    ("FGA0173", "INTERAÇÃO HUMANO COMPUTADOR"),
    ("FGA0313", "REQUISITOS DE SOFTWARE"),
    ("FGA0060", "SISTEMAS DE BANCO DE DADOS 2"),
    ("FGA0124", "PROJETO DE ALGORITMOS"),
    ("FGA0208", "ARQUITETURA E DESENHO DE SOFTWARE"),
    ("FGA0211", "FUNDAMENTOS DE REDES DE COMPUTADORES"),
    ("FGA0314", "TESTES DE SOFTWARE"),
    ("FGA0315", "QUALIDADE DE SOFTWARE 1"),
    ("FGA0109", "FUNDAMENTOS DE SISTEMAS EMBARCADOS"),
    ("FGA0210", "PARADIGMAS DE PROGRAMAÇÃO"),
    ("FGA0242", "TÉCNICAS DE PROGRAMAÇÃO EM PLATAFORMAS EMERGENTES"),
    ("FGA0244", "PROGRAMAÇÃO PARA SISTEMAS PARALELOS E DISTRIBUÍDOS"),
    ("FGA0288", "ESTÁGIO SUPERVISIONADO"),
    ("FGA0316", "ENGENHARIA DE PRODUTO DE SOFTWARE"),
    ("FGA0317", "GERÊNCIA DE CONFIGURAÇÃO E EVOLUÇÃO DE SOFTWARE"),
    ("FGA0287", "TRABALHO DE CONCLUSÃO DE CURSO 1"),
    ("FGA0304", "PROJETO INTEGRADOR DE ENGENHARIA 2"),
    ("FGA0290", "TRABALHO DE CONCLUSÃO DE CURSO 2"),
    ("FGA0318", "ATIVIDADE DE EXTENSÃO ENGENHARIA DE SOFTWARE"),
    ("CIC0191", "INTRODUÇÃO AO DESENVOLVIMENTO DE JOGOS"),
    ("ENM0080", "FENOMENOS DE TRANSPORTE"),
    ("FCTE0001", "FUNDAMENTOS LÓGICOS DE INTELIGÊNCIA ARTIFICIAL"),
    ("FCTE0002", "PARADIGMAS DE SOLUÇÃO DE PROBLEMAS"),
    ("FCTE0003", "ESTRUTURAS DE DADOS PARA COMPETIÇÕES"),
    ("FCTE0004", "MATEMÁTICA PARA COMPETIÇÕES"),
    ("FCTE0005", "ALGORITMOS EM GRAFOS"),
    ("FCTE0006", "GEOMETRIA COMPUTACIONAL"),
    ("FCTE0007", "ALGORITMOS EM STRINGS"),
    ("FEF0105", "PRÁTICA DESPORTIVA"),
    ("FGA0006", "FUNDAMENTOS DE EQUAÇÕES DIFERENCIAIS PARA ENGENHARIA"),
    ("FGA0008", "SISTEMAS AEROESPACIAIS"),
    ("FGA0027", "PRINCÍPIOS DE ROBÓTICA EDUCACIONAL"),
    ("FGA0028", "PROGRAMAÇÃO PARA COMPETIÇÕES"),
    ("FGA0031", "SEMINÁRIOS EM ENGENHARIA DE SOFTWARE"),
    ("FGA0034", "TÓPICOS ESPECIAIS EM MATEMÁTICA APLICADA"),
    ("FGA0038", "AERODINÂMICA DE SISTEMAS AEROESPACIAIS"),
    ("FGA0041", "TÓPICOS ESPECIAIS EM JOGOS DIGITAIS"),
    ("FGA0043", "DINÂMICA DOS GASES PARA SISTEMAS AEROESPACIAIS"),
    ("FGA0045", "MECÂNICA DO VÔO"),
    ("FGA0046", "MÉTODOS E TÉCNICAS DA ESCRITA CIENTÍFICA"),
    ("FGA0053", "TÓPICOS ESPECIAIS EM PROGRAMAÇÃO"),
    ("FGA0054", "TÓPICOS ESPECIAIS EM GOVERNANÇA DE TECNOLOGIA DA INFORMAÇÃO"),
    ("FGA0066", "FUNDAMENTOS DE VARIÁVEL COMPLEXA PARA ENGENHARIA"),
    ("FGA0072", "PRÁTICA DE ELETRÔNICA DIGITAL 2"),
    ("FGA0074", "TEORIA DE ELETRÔNICA DIGITAL 2"),
    ("FGA0083", "APRENDIZADO DE MÁQUINA"),
    ("FGA0084", "DESENVOLVIMENTO DE SOFTWARE"),
    ("FGA0090", "ONDULATÓRIA E FÍSICA TÉRMICA PARA ENGENHARIA"),
    ("FGA0111", "INTRODUÇÃO À WEB SEMÂNTICA"),
    ("FGA0112", "QUALIDADE DE SOFTWARE 2"),
    ("FGA0125", "INTRODUÇÃO À GEOMETRIA ANALÍTICA"),
    ("FGA0129", "PROCESSAMENTO DIGITAL DE SINAIS FINANCEIROS"),
    ("FGA0134", "TÓPICOS ESPECIAIS DE ENGENHARIA DE SOFTWARE"),
    ("FGA0144", "FÍSICA MODERNA"),
    ("FGA0148", "ENGENHARIA DE SEGURANÇA DO TRABALHO"),
    ("FGA0154", "MECANICA DOS SÓLIDOS 1 PARA ENGENHARIA"),
    ("FGA0155", "INTRODUÇÃO AO DESIGN E CONCEPÇÃO DE VEÍCULOS"),
    ("FGA0166", "ELEMENTOS E MÉTODOS EM ELETRÔNICA"),
    ("FGA0167", "SISTEMAS AUTOMOTIVOS"),
    ("FGA0169", "FONTES DE ENERGIA E TECNOLOGIAS DE CONVERSÃO"),
    ("FGA0171", "TÉCNICAS DE PROGRAMAÇÃO"),
    ("FGA0174", "DESENVOLVIMENTO SUSTENTÁVEL"),
    ("FGA0179", "MECANICA DOS SÓLIDOS 2 PARA ENGENHARIA"),
    ("FGA0181", "INOVAÇÃO"),
    ("FGA0186", "ELETRICIDADE APLICADA"),
    ("FGA0188", "MÉTODOS EXPERIMENTAIS PARA ENGENHARIA"),
    ("FGA0201", "PROJETO DE CIRCUITOS INTEGRADOS DIGITAIS"),
    ("FGA0203", "PLANEJAMENTO E GESTÃO DE ENERGIA"),
    ("FGA0204", "DINÂMICA DOS FLUÍDOS"),
    ("FGA0220", "SISTEMAS EMBARCADOS"),
    ("FGA0221", "INTELIGÊNCIA ARTIFICIAL"),
    ("FGA0226", "ELETRÔNICA VEICULAR"),
    ("FGA0254", "CIÊNCIAS AEROESPACIAIS"),
    ("FGA0264", "INTRODUÇÃO A COMPUTAÇÃO GRÁFICA"),
    ("FGA0265", "ECONOMIA DE ENERGIA"),
    ("FGA0274", "PRODUTIVIDADE E PROFISSIONALISMO EM ENGENHARIA DE SOFTWARE"),
    ("FGA0275", "ENGENHARIA DE SOFTWARE EXPERIMENTAL"),
    ("FGA0279", "PROGRAMAÇÃO WEB"),
    ("FGA0319", "GOVERNANÇA EM TECNOLOGIA DA INFORMAÇÃO"),
    ("FGA0320", "FELICIDADE"),
    ("FGA0321", "MELHORIA DE PROCESSOS DE SOFTWARE"),
    ("FGA0322", "INTRODUÇÃO À GAMIFICAÇÃO"),
    ("FGA0323", "ATIVIDADE COMPLEMENTAR"),
    ("FGA0324", "ATIVIDADE COMPLEMENTAR"),
    ("FGA0325", "ATIVIDADE COMPLEMENTAR"),
    ("FGA0326", "ATIVIDADE COMPLEMENTAR"),
    ("FGA0327", "ATIVIDADE COMPLEMENTAR"),
    ("FGA0328", "ATIVIDADE COMPLEMENTAR"),
    ("FTD0007", "INTRODUCAO A ATIVIDADE EMPRESARIAL"),
    ("LIP0174", "LÍNGUA DE SINAIS BRASILEIRA - BÁSICO"),
    ("MAT0027", "CÁLCULO 3"),
    ("MAT0038", "TEORIA DOS NÚMEROS 1"),
]

def insert_disciplines():
    session = SessionLocal()
    for code, name in disciplines_data:
        discipline = Discipline(discipline_code=code, discipline_name=name)
        session.add(discipline)
    session.commit()
    session.close()
    print("Disciplinas inseridas com sucesso!")


if __name__ == '__main__':
    recreate_db()
    insert_disciplines()