"""Adicionando Usuario, Disciplina e Relacionamentos

Revision ID: 787c6c8399f8
Revises: 8ac8a4ebfb0f
Create Date: 2025-02-04 19:45:14.539811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '787c6c8399f8'
down_revision: Union[str, None] = '8ac8a4ebfb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=False)
    op.create_table('Discipline',
    sa.Column('discipline_code', sa.String(), nullable=False),
    sa.Column('discipline_name', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['User.email'], ),
    sa.PrimaryKeyConstraint('discipline_code')
    )
    op.create_index(op.f('ix_Discipline_discipline_code'), 'Discipline', ['discipline_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Discipline_discipline_code'), table_name='Discipline')
    op.drop_table('Discipline')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
