"""Nova coluna degree_level em Course

Revision ID: 8ac8a4ebfb0f
Revises: e109e83ab136
Create Date: 2025-02-02 09:20:02.918769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ac8a4ebfb0f'
down_revision: Union[str, None] = 'e109e83ab136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Course', sa.Column('degree_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Course', 'degree_level')
    # ### end Alembic commands ###
